{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core-graph.componentName" (dict "Release" .Release "Chart" .Chart "component" "postgres") }}-secret
  labels:
    {{- include "core-graph.labels" . | nindent 4 }}
    {{- include "core-graph.selectorLabels" (dict "Release" .Release "component" "postgres") | nindent 4 }}
type: Opaque
stringData:
  password: {{ .Values.postgres.auth.password | quote }}
{{- end }}
