apiVersion: v1
kind: Secret
metadata:
  name: {{ include "core-graph.componentName" (dict "Release" .Release "Chart" .Chart "component" "api") }}-secret
  labels:
    {{- include "core-graph.labels" . | nindent 4 }}
type: Opaque
stringData:
  pg-dsn: {{ include "core-graph.postgresDSN" . | quote }}
