apiVersion: v1
kind: Service
metadata:
  name: {{ include "core-graph.componentName" (dict "Release" .Release "Chart" .Chart "component" "api") }}
  labels:
    {{- include "core-graph.labels" . | nindent 4 }}
    {{- include "core-graph.selectorLabels" (dict "Release" .Release "component" "api") | nindent 4 }}
spec:
  selector:
    {{- include "core-graph.selectorLabels" (dict "Release" .Release "component" "api") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: http
      protocol: TCP
